### ISSUE TITLE
Condition based on issue tag

### ISSUE THREAD

**Issue by onovotny** [konradpabjan/actions-add-new-issue-to-column#2]
If I want to have this action run only for issues with a specific tag (new issue with tag/tag added to existing issue), can I do that? I'm not quite sure how to filter the events.

**Comment by rachmari** [comment]
@clairernovotny I'm not sure if this is what you're looking for, but I use this action to triage issues with specific labels to a project board. For example:

```
- name: Triage to my project board
  uses: konradpabjan/actions-add-new-issue-to-column@v1.1
  if: contains(github.event.issue.labels.*.name, 'high-priority') || contains(github.event.issue.labels.*.name, 'needs-fr'))
  with:
    action-token: ${{ secrets.MY_SUPER_SECRET }}
    project-url: "https://github.com/orgs/octo-org/projects/1234"
    column-name: "Needs triage"     
```
