### ISSUE TITLE
#ERROR# TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by brandonh-msft** [konradpabjan/actions-add-new-issue-to-column#21]
See this run: https://github.com/dotnet/upgrade-assistant/actions/runs/3093629638/jobs/5006207314#step:2:8

Not really sure what's going wrong

**Comment by hu3man** [comment]
Also seeing the same thing: https://github.com/ecadlabs/taqueria/actions/runs/3285952561

Workflow config:
```
name: Add new PR's to the scrum board

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  add-pr-to-taqueria-dev-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
    - name: New PR
      if: ${{ !github.event.pull_request.ready_for_review }}
      uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.ADD_TO_PROJECT_PAT }}"
        project-url: "https://github.com/orgs/ecadlabs/projects/9"
        column-name: "🚀  Current Sprint"
    - name: PR Ready for review
      if: ${{ github.event.pull_request.ready_for_review }}
      uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.ADD_TO_PROJECT_PAT }}"
        project-url: "https://github.com/orgs/ecadlabs/projects/9"
        column-name: "👀 In review"
```
